# IMPORTS HERE

In [134]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

# Data Preparation

In [135]:
df = pd.read_csv('data/dataset_1st/training.csv')

In [136]:
df.isnull()

,txkey,locdt,loctm,chid,cano,contp,etymd,mchno,acqic,mcc,...,stocn,scity,stscd,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk,label
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688521,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
8688522,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
8688523,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
8688524,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
8688525,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [137]:
df.isna().any()

txkey        False
locdt        False
loctm        False
chid         False
cano         False
contp        False
etymd         True
mchno        False
acqic        False
mcc           True
conam        False
ecfg         False
insfg        False
iterm        False
bnsfg        False
flam1        False
stocn         True
scity         True
stscd         True
ovrlt        False
flbmk        False
hcefg         True
csmcu         True
csmam        False
flg_3dsmk    False
label        False
dtype: bool

In [138]:
dropCol = ['chid', 'cano', 'mchno', 'acqic', 'stscd']
df = df.drop(columns = dropCol)
df = df.dropna()
df.isna().any()

txkey        False
locdt        False
loctm        False
contp        False
etymd        False
mcc          False
conam        False
ecfg         False
insfg        False
iterm        False
bnsfg        False
flam1        False
stocn        False
scity        False
ovrlt        False
flbmk        False
hcefg        False
csmcu        False
csmam        False
flg_3dsmk    False
label        False
dtype: bool

In [139]:
df_label_0 = df[df['label'] == 0]
df_label_0

,txkey,locdt,loctm,contp,etymd,mcc,conam,ecfg,insfg,iterm,...,flam1,stocn,scity,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk,label
0,1c09727c939eb69ead2a4ce4072b8aa18992a64f01fcb4...,46,101812,5,1.0,375.0,1524.0,0,0,0.0,...,1529,0.0,15759.0,0,0,6.0,70.0,1529,0,0
1,2043f245a93bc6328dac964d6dbc89f13a0346062c194d...,17,85509,5,8.0,282.0,101.0,1,0,0.0,...,101,0.0,15759.0,0,0,8.0,70.0,101,0,0
2,e4853710290a8409279f3279f8032ae670824bd19aa173...,44,212641,5,4.0,288.0,117.0,0,0,0.0,...,116,0.0,15759.0,0,0,6.0,70.0,116,0,0
3,74d811b1dbc28b22b73ba2c79bb6033791d913b6d27a25...,42,102702,5,1.0,375.0,1676.0,0,0,0.0,...,1683,0.0,15759.0,0,0,6.0,70.0,1683,0,0
4,68ca182343969d429d79a34e532bc1ca7a3cc032c2ad81...,31,185737,5,5.0,406.0,14.0,1,0,0.0,...,14,0.0,15759.0,0,0,6.0,70.0,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688521,fe5788aae7affa13a3946608670d7cdb9b4cde44f8f2cf...,14,84737,5,4.0,282.0,49.0,0,0,0.0,...,49,0.0,15759.0,0,0,0.0,70.0,49,0,0
8688522,8a2b5b7ba4443c311f06be147e42e7493735ae203c48ba...,23,105923,5,4.0,276.0,4020.0,0,0,0.0,...,4018,0.0,15759.0,0,0,6.0,70.0,4018,0,0
8688523,15a9ef847ce3702a176abfaceedf9a22a328e27a0c99a9...,23,141030,5,4.0,272.0,315.0,0,0,0.0,...,314,0.0,11380.0,0,0,6.0,70.0,314,0,0
8688524,2ed4454b4fcce6b9f98c3c22a1df941f03beb14bce94ea...,10,120209,5,5.0,272.0,226.0,1,0,0.0,...,225,0.0,15759.0,0,0,6.0,70.0,225,0,0
8688525,eb17de9aad63d3baa82eb2c59c3760287a53d7c9a57588...,4,15317,5,8.0,309.0,165.0,1,0,0.0,...,166,0.0,15759.0,0,0,6.0,70.0,166,0,0

In [140]:
df_label_1 = df[df['label'] == 1]
df_label_1

,txkey,locdt,loctm,contp,etymd,mcc,conam,ecfg,insfg,iterm,...,flam1,stocn,scity,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk,label
318,7773d6012a013a75d57891ba6dd96f464e04720b9d699c...,0,190457,5,5.0,482.0,5741.00,1,0,0.0,...,5752,49.0,5441.0,0,0,6.0,70.0,5752,0,1
339,cded61d4f4c719c1a418e8348509763f1591b6f7f7d3f7...,49,204814,5,8.0,324.0,33.00,1,0,0.0,...,33,126.0,10300.0,0,0,6.0,70.0,33,0,1
881,78bcabfbe831b5057b5be29501e50c3e95a0f777146f8c...,19,43049,5,8.0,276.0,0.00,1,0,0.0,...,0,126.0,8067.0,0,0,6.0,68.0,0,0,1
1576,8722c91641e9c08e31fd94bf094be60f6bc10df05c6b84...,47,213335,5,5.0,390.0,1202.83,1,0,0.0,...,1201,29.0,17279.0,0,0,6.0,81.0,38,0,1
1598,21c86f81f00a2aa393f649a1b189254b89d8c5afa292b3...,14,213413,5,5.0,324.0,1790.00,1,0,0.0,...,1797,61.0,15955.0,0,0,6.0,70.0,1797,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8686800,d00b17a3c71c968e7ff511fe1c0b2915a72aacab5a3e04...,48,33914,5,8.0,324.0,50.00,1,0,0.0,...,50,126.0,13091.0,0,0,6.0,70.0,50,0,1
8686969,459a285e001dfed37e213fcd9a2b46373796a686ad4ab5...,26,100301,4,5.0,352.0,774.00,1,0,0.0,...,773,22.0,10755.0,0,0,6.0,70.0,773,0,1
8687406,d445af80114da7348d32dfcf0cef49d2fdfee3effdaa36...,14,95753,4,1.0,353.0,0.00,0,0,0.0,...,0,126.0,15646.0,0,0,6.0,68.0,0,0,1
8687798,179f57a3ca3a9a7f629162322d97a34655fdb34ea9963d...,44,63707,5,1.0,324.0,490.00,1,0,0.0,...,491,126.0,10300.0,0,0,6.0,70.0,491,0,1
8688516,566b990ac3203d04a540514bfb564015ed17efdf12bfee...,12,134521,5,5.0,324.0,779.00,1,0,0.0,...,781,113.0,12885.0,0,0,6.0,70.0,781,0,1

In [141]:
label_0_rows = len(df_label_0)
label_1_rows = len(df_label_1)
min_rows = min(label_0_rows, label_1_rows)

df_label_0_sample = df_label_0.sample(n = min_rows, random_state = 42)
df_label_1_sample = df_label_1.sample(n = min_rows, random_state = 42)

balanced_df = pd.concat([df_label_0_sample, df_label_1_sample])
balanced_df

,txkey,locdt,loctm,contp,etymd,mcc,conam,ecfg,insfg,iterm,...,flam1,stocn,scity,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk,label
658684,8df9410491b0ab93617672a6fcb39d324418a155540d73...,6,93753,5,4.0,282.0,666.00,0,0,0.0,...,668,0.0,15759.0,0,0,6.0,70.0,668,0,0
1067937,e447ce38457a7cda2cfff1b0141fa8c858ff0f7d408241...,17,182022,5,4.0,282.0,188.00,0,0,0.0,...,189,0.0,15759.0,0,0,0.0,70.0,189,0,0
1936351,73fa87a86767926f56edb38c6d2a4d6cef20197560a5f1...,51,75404,5,5.0,276.0,59.00,1,0,0.0,...,59,0.0,15759.0,0,0,6.0,70.0,59,0,0
4294607,f4354d9bba07f2253c40b522d7976f9183bbe892847563...,22,152041,5,8.0,406.0,4.69,1,0,0.0,...,5,42.0,17185.0,0,0,6.0,76.0,3,0,0
879406,18c5a14690dc75313e7dc6616656ca8e308ff80bb621bc...,52,115618,4,1.0,348.0,14900.00,1,0,0.0,...,14922,0.0,15759.0,0,0,6.0,70.0,14922,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8241384,ed952befea116cd816e7045074691844b59f3809c4949a...,30,90509,5,8.0,390.0,94.71,1,0,0.0,...,94,42.0,69.0,0,0,6.0,68.0,3,0,1
1490572,e4abfd269ba46781e05d115c663d288c64337e80799efe...,17,4725,5,5.0,326.0,2990.00,1,0,0.0,...,2995,126.0,10300.0,0,0,6.0,70.0,2995,0,1
246176,9a3c02c8057496943f3b2b09831258d8d161067de957d4...,41,60820,5,5.0,326.0,510.00,1,0,0.0,...,512,54.0,11170.0,0,0,6.0,70.0,512,0,1
4341186,116223812a4aaacc8a810a80fea587f8fef242b24bd509...,48,2054,5,1.0,325.0,300.00,1,0,0.0,...,299,126.0,5959.0,0,0,6.0,70.0,299,0,1
6528668,ccee42f69840781a5ed5bd8102025f931ee11dac0c936d...,47,134334,5,5.0,406.0,64385.85,1,0,0.0,...,64418,31.0,4574.0,1,0,6.0,68.0,2000,0,1

In [142]:
balanced_df.keys()

Index(['txkey', 'locdt', 'loctm', 'contp', 'etymd', 'mcc', 'conam', 'ecfg',
       'insfg', 'iterm', 'bnsfg', 'flam1', 'stocn', 'scity', 'ovrlt', 'flbmk',
       'hcefg', 'csmcu', 'csmam', 'flg_3dsmk', 'label'],
      dtype='object')

In [149]:
X1 = balanced_df['locdt'].values      #授權日期
X2 = balanced_df['loctm'].values      #授權時間
X3 = balanced_df['contp'].values      #交易類別
X4 = balanced_df['etymd'].values      #交易型態
X5 = balanced_df['mcc'].values        #mcc_code
X6 = balanced_df['conam'].values      #交易金額-台幣
X7 = balanced_df['ecfg'].values       #網路交易註記
X8 = balanced_df['insfg'].values      #是否分期交易
X9 = balanced_df['iterm'].values      #分期期數
X10 = balanced_df['bnsfg'].values     #是否紅利交易
X11 = balanced_df['flam1'].values     #實付金額
X12 = balanced_df['stocn'].values     #消費地國別
X13 = balanced_df['scity'].values     #消費城市  
X14 = balanced_df['ovrlt'].values     #超額註記碼
X15 = balanced_df['flbmk'].values     #Fallback註記
X16 = balanced_df['hcefg'].values     #支付型態
X17 = balanced_df['csmcu'].values     #消費地幣別
X18 = balanced_df['csmam'].values     #消費地金額
X19 = balanced_df['flg_3dsmk'].values #3D交易註記
Y = balanced_df['label'].values       #盜刷與否

X = np.array(list(zip(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19)))
#X = X.reshape(-1,1)


model = linear_model.LogisticRegression(solver='lbfgs', max_iter = 100000)
model.fit(X, Y)

prediction = model.predict(X)

accuracy_train = model.score(X, Y)


coefficients = list(model.coef_[0])
intercept = model.intercept_[0]

print(("accuracy: %.3f " % (accuracy_train*100)) + "%")
print("coefficient: ", coefficients)
print("intercept: ", intercept)

accuracy: 89.309 %
coefficient:  [0.0069867967448464605, -1.1549086407645924e-06, -6.483470806789159e-05, 0.0010010034670448374, 0.0070986998338290926, -0.003919717544815481, 0.0005908776434476846, -4.910937642716622e-05, -0.0003067848155737342, -3.1966513280941446e-06, 0.003969365097572587, 0.03924805273222915, -0.0001398208995281093, 9.682130265448258e-05, 9.464899554463851e-07, 0.0016547072138400076, -0.03274067765766672, -7.231961894931169e-08, -0.00013782448633338048]
intercept:  -3.516389486123869e-05

In [144]:
def predict_equation(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19):

    value = (x1 * coefficients[0]) + (x2 * coefficients[1]) + (x3 * coefficients[2]) + (x4 * coefficients[3]) + (x5 * coefficients[4]) + (x6 * coefficients[5]) + (x7 * coefficients[6]) + (x8 * coefficients[7]) + (x9 * coefficients[8]) + (x10 * coefficients[9]) + (x11 * coefficients[10]) + (x12 * coefficients[11]) + (x13 * coefficients[12]) + (x14 * coefficients[13]) + (x15 * coefficients[14]) + (x16 * coefficients[15]) + (x17 * coefficients[16]) + (x18 * coefficients[17]) + (x19 * coefficients[18]) + intercept
    
    if value < 0.5:
        return 0
    else:
        return 1

In [145]:
df2 = pd.read_csv('data/dataset_1st/public_processed.csv')
df2

,txkey,locdt,loctm,chid,cano,contp,etymd,mchno,acqic,mcc,...,flam1,stocn,scity,stscd,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk
0,a2c1209018e4e52e04f6fabb48f05f1b8bc09dc838ff6c...,56,105157,d6d145d0d058e3f63b9ec421cf9e1543b0c3e059d18c2c...,9c454e0cf3680075b0382394ca59b00ee9435fd829da29...,4,1.0,8be206f97d10b57a46ea0ef5527155a0f9b48d16255b70...,2a608b081c09492bd2bc96d7def5371c4bc9cabf324a98...,272.0,...,1349,0.0,15759.0,NaN,0,0,6.0,70.0,1349,0
1,16c4880500059e01553789be11bbb50753b7acaae7b95b...,56,185520,b599fb83473599fa2df4a04136a668c28df7914293f1da...,9f097cba6a70333c906904ebaad438356cf75b6abf5dd4...,5,8.0,dd280b4f35a02701142ba7de47abb9736deca3eed86474...,46f63555d29f177290dfe20e989146fb033e453f1d5ff3...,320.0,...,306,0.0,13451.0,NaN,0,0,6.0,70.0,306,0
2,623c56be3bee87724e3d119c271d9ed098eeda84233183...,59,102312,8de197129150d454df1639e9743c1aa11b1c1122a2010c...,439691cb167b272661c2eb9073124f5d422f446b0f92fb...,5,1.0,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,494.0,...,20,0.0,15759.0,NaN,0,0,NaN,NaN,0,0
3,250da12187059cf6e3a3066656a2919d08ceb8207efd55...,58,230138,f9cbad08a76f1dd9736a4fc51255eb55637ec0a417a406...,992679b728784192c17e90939918cbfae32ad1222fad26...,5,5.0,bd2b3523b4ecd652445b75ea7583c92f6f02af3971251b...,70dac5b1dfde828f556a93321a649df72891db35430588...,272.0,...,8339,42.0,12381.0,NaN,0,0,6.0,70.0,8339,0
4,4b268e0da036f44cbbb056ddfac6a28ea336d9cf299843...,59,101937,27d235e691a425098f291105f78f9877e05bb75e1f132b...,763fd2a91420f9b632c378ca82ff9e318851fa1964cbba...,5,5.0,156987f72b8993b8c5a898fa76f3b8e6454e10e18aa238...,89b1654aaef0b65b1868004cfdce2dcbb67f15b7fba535...,217.0,...,163,126.0,14786.0,NaN,0,0,6.0,68.0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600177,741a391b2c2114491d1d18acb1a892341b9280e1e3529f...,56,93445,2682f330b73282799bf3ef541bae705d514c5db39294cf...,22140589fb47e13001536d7bb184c49787fa8e48b1428e...,4,1.0,d5375a34f62be5545856ecffe8b6351298d443081845b9...,13624921218432873e0cfa1966e41376844b387695a0ee...,231.0,...,96,0.0,16117.0,NaN,0,0,6.0,70.0,96,0
600178,76f613595631fb35938bf10f5b7abe3f60a3d34ccf5f44...,56,145420,dda3e682f516da803061ac325237915fcda57c6c02295a...,0e021870d9c50e284e8d792b3834579acdac17972d5932...,5,5.0,d3c72a48a61829f273204d8ea5edba4172fb49370aa9e6...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,375.0,...,2017,0.0,15759.0,NaN,0,0,6.0,70.0,2017,0
600179,c32e846a4469e4869e2df8f8e160fba4e829b6beebb44d...,58,3400,4f745fe0a5c2bd94c7e5425b5c9f46ab2a9e49aff504b7...,477a9201460a4201b9599ee8e85e9c4ed0586c8e18fac4...,5,1.0,45b6cb170af96950ffd009b6275bb22f5f5b052687d237...,839aa8d49064459ddd81fcb39ca4e3420577b8faa0db91...,406.0,...,33,126.0,10300.0,NaN,0,0,6.0,70.0,33,0
600180,d641cd25a830de759cd55b4a643d71eadb770bc917aed3...,59,134901,c9f4c0549ba75e96ab85f3638f3b83167757d6716c7a6b...,4e9975c655afe0fcf6f226c49e50082ec5146584cd1ef9...,5,4.0,02374f9c035510cd74701576d1246a65895db64ebf8021...,8f6b3ff512a001e0d1988c6cd888ef8c74112fb71117e5...,288.0,...,1796,0.0,15759.0,NaN,0,0,6.0,70.0,1796,0
600181,301d0262bdd594a886446ddca09b4a21bef51dddf9618a...,56,220238,8f12d0d4eda2578df72a958e532d627996e5f067ad7b48...,6139394400615fea7f8b06cf2891fe82f69594081a099c...,5,8.0,e9fdf703d8d347bbdd35e1300392e101d1a28b7bb492fd...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,276.0,...,239,0.0,15759.0,NaN,0,0,1.0,70.0,239,0

In [150]:
T1 = df2['locdt']
T2 = df2['loctm']
T3 = df2['contp']
T4 = df2['etymd']
T5 = df2['mcc']
T6 = df2['conam']
T7 = df2['ecfg']
T8 = df2['insfg']
T9 = df2['iterm']
T10 = df2['bnsfg']
T11 = df2['flam1']
T12 = df2['stocn']
T13 = df2['scity'] 
T14 = df2['ovrlt']
T15 = df2['flbmk']
T16 = df2['hcefg']
T17 = df2['csmcu'] 
T18 = df2['csmam']
T19 = df2['flg_3dsmk']
predict_result = []


for i in range(0,len(df2)):
    predict_result.append(predict_equation(T1[i],T2[i],T3[i],T4[i],T5[i],T6[i],T7[i],T8[i],T9[i],T10[i],T11[i],T12[i],T13[i],T14[i],T15[i],T16[i],T17[i],T18[i],T19[i]))

print(predict_result[:1000])

print("total frauds: %d" % sum(predict_result))
print("percentage of faruds: %.2f" % ((100 * sum(predict_result))/len(predict_result)) + "%")

[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0]
total frauds: 90078
percentage of faruds: 15.01%